# Generated by Django 5.1.1 on 2024-10-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0017_alter_productos_tipo'),
        ('users', '0002_alter_usuario_direccion_alter_usuario_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(default=0)),
                ('texto_comentario', models.TextField()),
                ('fecha_comentario', models.DateField(auto_now=True)),
                ('producto_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_producto', to='Productos.productos')),
                ('usuario_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_usuario', to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField()),
                ('respuesta_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_comentario', to='comentarios.comentario')),
                ('usuario_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_de_usuario', to='users.usuario')),
                ('usuario_respuesta_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_usuario', to='users.usuario')),
            ],
        ),
    ]
