# Generated by Django 5.1.1 on 2024-10-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestas',
            old_name='usuario_respuesta',
            new_name='usuario_responde',
        ),
    ]
