# Generated by Django 5.1.1 on 2024-10-17 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_datosusuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosusuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='datos',
        ),
        migrations.AddField(
            model_name='datosusuario',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AddField(
            model_name='datosusuario',
            name='telefono',
            field=models.CharField(default='Sin telefono', max_length=20),
        ),
        migrations.AddField(
            model_name='datosusuario',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('casual', 'Casual'), ('admin', 'Admin')], default='casual', max_length=10),
        ),
    ]
