# Generated by Django 5.1.1 on 2024-10-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
