# Generated by Django 5.1.1 on 2024-10-01 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='producto',
            field=models.ForeignKey(blank=True, default='Bicicletas', on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='Productos.productos'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(max_length=255),
        ),
    ]
