# Generated by Django 5.1.1 on 2024-10-02 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_alter_productos_categoria_alter_productos_imagen'),
        ('usuarios', '0003_usuario_user_alter_usuario_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='usuarios.usuario'),
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='Productos.categoria'),
        ),
    ]
