# Generated by Django 5.1.1 on 2024-10-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_productos_usuario_remove_productos_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='usuario',
        ),
    ]
