# Generated by Django 5.1.1 on 2024-10-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0009_remove_productos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
    ]
