# Generated by Django 5.1.1 on 2024-10-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_remove_categoria_producto_remove_productos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='Productos.categoria'),
        ),
    ]
