# Generated by Django 5.1.1 on 2024-10-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0012_alter_productos_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
    ]
