# Generated by Django 5.1.1 on 2024-10-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0016_alter_productos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(choices=[('Electrica', 'Electrica'), ('Montaña', 'Montaña'), ('Ruta', 'Ruta'), ('BMX', 'BMX'), ('Nutrición', 'Nutrición'), ('Ropa', 'Ropa'), ('Partes', 'Partes')], default='Bicicletas', max_length=255),
        ),
    ]
